import React from 'react';

const PrivacyPolicy = () => {
  return (
    <div className="max-w-4xl mx-auto p-6 bg-white shadow-md rounded-lg mt-10 dark:bg-gray-800">
      <h1 className="text-3xl font-bold mb-4 text-blue-700 dark:text-blue-300">
        Privacy Policy
      </h1>
      <p className="text-gray-600 mb-6 dark:text-gray-400">
        Last updated: February 19, 2025
      </p>
      <p className="mb-4 dark:text-gray-300">
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p className="mb-6 dark:text-gray-300">
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>
      <h2 className="text-2xl font-semibold text-blue-600 mt-6 mb-2 dark:text-blue-400">
        Interpretation and Definitions
      </h2>
      <h3 className="text-xl font-semibold text-gray-700 mt-4 dark:text-gray-300">
        Interpretation
      </h3>
      <p className="mb-4 dark:text-gray-300">
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions.
      </p>
      <h3 className="text-xl font-semibold text-gray-700 mt-4 dark:text-gray-300">
        Definitions
      </h3>
      <ul className="list-disc list-inside mb-6 dark:text-gray-300">
        <li>
          <strong>Account</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </li>
        <li>
          <strong>Affiliate</strong> means an entity that controls, is
          controlled by or is under common control with a party, where "control"
          means ownership of 50% or more of the shares, equity interest or other
          securities entitled to vote for election of directors or other
          managing authority.
        </li>
        <li>
          <strong>Company</strong> (referred to as either "the Company", "We",
          "Us" or "Our" in this Agreement) refers to Simplium Technologies,
          Office No. 37, First Floor, Sagar Complex, Kasarwadi, Pune-411034.
        </li>
        <li>
          <strong>Cookies</strong> are small files that are placed on Your
          computer, mobile device or any other device by a website, containing
          the details of Your browsing history on that website among its many
          uses.
        </li>
        <li>
          <strong>Country</strong> refers to: India
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service
          such as a computer, a cellphone or a digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Website.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person
          who processes the data on behalf of the Company. It refers to
          third-party companies or individuals employed by the Company to
          facilitate the Service, to provide the Service on behalf of the
          Company, to perform services related to the Service or to assist the
          Company in analyzing how the Service is used.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong>Website</strong> refers to Simpli Collect, accessible from{' '}
          <a
            href="http://simplicollect.in"
            className="underline dark:text-blue-300"
          >
            https://simplicollect.in/
          </a>
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </li>
      </ul>
      <h2 className="text-2xl font-semibold text-blue-600 mt-6 mb-2 dark:text-blue-400">
        Collecting and Using Your Personal Data
      </h2>
      <h3 className="text-xl font-semibold text-gray-700 mt-4 dark:text-gray-300">
        Types of Data Collected
      </h3>
      <h4 className="text-lg font-semibold text-gray-600 mt-3 dark:text-gray-300">
        Personal Data
      </h4>
      <p className="mb-4 dark:text-gray-300">
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul className="list-disc list-inside mb-6 dark:text-gray-300">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Usage Data</li>
      </ul>
      <h3 className="text-xl font-semibold text-gray-700 mt-4 dark:text-gray-300">
        Usage Data
      </h3>
      <p className="mb-3 dark:text-gray-300">
        Usage Data is collected automatically when using the Service.
      </p>
      <p className="mb-3 dark:text-gray-300">
        Usage Data may include information such as Your Device's Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </p>
      <p className="mb-3 dark:text-gray-300">
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other
        diagnostic data.
      </p>
      <p className="mb-6 dark:text-gray-300">
        We may also collect information that Your browser sends whenever You
        visit our Service or when You access the Service by or through a mobile
        device.
      </p>
      <h2 className="text-2xl font-semibold text-blue-600 mt-6 mb-2 dark:text-blue-400">
        Tracking Technologies and Cookies
      </h2>
      <p className="mb-4 dark:text-gray-300">
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. Tracking technologies used
        are beacons, tags, and scripts to collect and track information and to
        improve and analyze Our Service. The technologies We use may include:
      </p>
      <p className="mb-4 dark:text-gray-300">
        Cookies or Browser Cookies. A cookie is a small file placed on Your
        Device. You can instruct Your browser to refuse all Cookies or to
        indicate when a Cookie is being sent. However, if You do not accept
        Cookies, You may not be able to use some parts of our Service. Unless
        you have adjusted Your browser setting so that it will refuse Cookies,
        our Service may use Cookies.
      </p>
      <p className="mb-4 dark:text-gray-300">
        Web Beacons. Certain sections of our Service and our emails may contain
        small electronic files known as web beacons (also referred to as clear
        gifs, pixel tags, and single-pixel gifs) that permit the Company, for
        example, to count users who have visited those pages or opened an email
        and for other related website statistics (for example, recording the
        popularity of a certain section and verifying system and server
        integrity).
      </p>
      <p className="mb-4 dark:text-gray-300">
        Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
        remain on Your personal computer or mobile device when You go offline,
        while Session Cookies are deleted as soon as You close Your web browser.
        You can learn more about cookies on TermsFeed website article.
      </p>
      <p className="mb-4 dark:text-gray-300">
        We use both Session and Persistent Cookies for the purposes set out
        below:
      </p>
      <ul className="list-disc list-inside mb-6 dark:text-gray-300">
        <li>
          <strong>Necessary / Essential Cookies</strong>
          <ul className="list-disc list-inside ml-6 dark:text-gray-300">
            <li>Type: Session Cookies</li>
            <li>Administered by: Us</li>
            <li>
              Purpose: These Cookies are essential to provide You with services
              available through the Website and to enable You to use some of its
              features. They help to authenticate users and prevent fraudulent
              use of user accounts. Without these Cookies, the services that You
              have asked for cannot be provided, and We only use these Cookies
              to provide You with those services.
            </li>
          </ul>
        </li>
        <li>
          <strong>Cookies Policy / Notice Acceptance Cookies</strong>
          <ul className="list-disc list-inside ml-6 dark:text-gray-300">
            <li>Type: Persistent Cookies</li>
            <li>Administered by: Us</li>
            <li>
              Purpose: These Cookies identify if users have accepted the use of
              cookies on the Website.
            </li>
          </ul>
        </li>
        <li>
          <strong>Functionality Cookies</strong>
          <ul className="list-disc list-inside ml-6 dark:text-gray-300">
            <li>Type: Persistent Cookies</li>
            <li>Administered by: Us</li>
            <li>
              Purpose: These Cookies allow us to remember choices You make when
              You use the Website, such as remembering your login details or
              language preference. The purpose of these Cookies is to provide
              You with a more personal experience and to avoid You having to
              re-enter your preferences every time You use the Website.
            </li>
          </ul>
        </li>
      </ul>
      <h2 className="text-2xl font-semibold text-blue-600 mt-6 mb-2 dark:text-blue-400">
        Use of Your Personal Data
      </h2>
      <p className="mb-4 dark:text-gray-300">
        The Company may use Personal Data for the following purposes:
      </p>
      <ul className="list-disc pl-6 space-y-2 mb-6 dark:text-gray-300">
        <li>
          <strong>To provide and maintain our Service:</strong> Including to
          monitor the usage of our Service.
        </li>
        <li>
          <strong>To manage Your Account:</strong> To manage Your registration
          as a user of the Service. The Personal Data You provide can give You
          access to different functionalities of the Service that are available
          to You as a registered user.
        </li>
        <li>
          <strong>For the performance of a contract:</strong> The development,
          compliance, and undertaking of the purchase contract for the products,
          items, or services You have purchased or of any other contract with Us
          through the Service.
        </li>
        <li>
          <strong>To contact You:</strong> By email, telephone calls, SMS, or
          other equivalent forms of electronic communication, such as push
          notifications, regarding updates or informative communications related
          to the functionalities, products, or contracted services, including
          security updates when necessary.
        </li>
        <li>
          <strong>To provide You with news and offers:</strong> Special offers
          and general information about other goods, services, and events
          similar to those you have already purchased or enquired about, unless
          You have opted out.
        </li>
        <li>
          <strong>To manage Your requests:</strong> To attend and manage Your
          requests to Us.
        </li>
        <li>
          <strong>For business transfers:</strong> We may use Your information
          to evaluate or conduct a merger, restructuring, sale, or transfer of
          some or all of Our assets, in which Personal Data held by Us about our
          Service users is among the assets transferred.
        </li>
        <li>
          <strong>For other purposes:</strong> We may use Your information for
          data analysis, identifying usage trends, determining the effectiveness
          of promotional campaigns, and improving our Service, products,
          marketing, and user experience.
        </li>
      </ul>
      <p className="mb-4 dark:text-gray-300">
        We may share Your personal information in the following situations:
      </p>
      <ul className="list-disc pl-6 space-y-2 dark:text-gray-300">
        <li>
          <strong>With Service Providers:</strong> To monitor and analyze the
          use of our Service, and to contact You.
        </li>
        <li>
          <strong>For business transfers:</strong> In connection with, or during
          negotiations of, any merger, sale of Company assets, financing, or
          acquisition of all or a portion of Our business to another company.
        </li>
        <li>
          <strong>With Affiliates:</strong> We may share Your information with
          Our affiliates, in which case we require them to honor this Privacy
          Policy. Affiliates include Our parent company and subsidiaries.
        </li>
        <li>
          <strong>With business partners:</strong> To offer You certain
          products, services, or promotions.
        </li>
        <li>
          <strong>With other users:</strong> When You share personal information
          in public areas, it may be viewed by all users and publicly
          distributed outside.
        </li>
        <li>
          <strong>With Your consent:</strong> We may disclose Your personal
          information for any other purpose with Your consent.
        </li>
      </ul>
      <h2 className="text-2xl font-semibold text-blue-600 mt-6 mb-2 dark:text-blue-400">
        Retention of Your Personal Data
      </h2>
      <p className="mb-3 dark:text-gray-300">
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use Your Personal Data to the extent necessary to comply with
        our legal obligations (for example, if we are required to retain your
        data to comply with applicable laws), resolve disputes, and enforce our
        legal agreements and policies.
      </p>
      <p className="mb-6 dark:text-gray-300">
        The Company will also retain Usage Data for internal analysis purposes.
        Usage Data is generally retained for a shorter period of time, except
        when this data is used to strengthen the security or to improve the
        functionality of Our Service, or We are legally obligated to retain this
        data for longer time periods.
      </p>
      <h2 className="text-2xl font-semibold text-blue-600 mt-6 mb-2 dark:text-blue-400">
        Transfer of Your Personal Data
      </h2>
      <p className="mb-2 dark:text-gray-300">
        Your information, including Personal Data, is processed at the Company's
        operating offices and in any other places where the parties involved in
        the processing are located. It means that this information may be
        transferred to — and maintained on — computers located outside of Your
        state, province, country or other governmental jurisdiction where the
        data protection laws may differ than those from Your jurisdiction.
      </p>
      <p className="mb-2 dark:text-gray-300">
        Your consent to this Privacy Policy followed by Your submission of such
        information represents Your agreement to that transfer.
      </p>
      <p className="mb-6 dark:text-gray-300">
        The Company will take all steps reasonably necessary to ensure that Your
        data is treated securely and in accordance with this Privacy Policy and
        no transfer of Your Personal Data will take place to an organization or
        a country unless there are adequate controls in place including the
        security of Your data and other personal information.
      </p>
      <h2 className="text-2xl font-semibold text-blue-600 mt-6 mb-2 dark:text-blue-400">
        Delete Your Personal Data
      </h2>
      <p className="mb-3 dark:text-gray-300">
        You have the right to delete or request that We assist in deleting the
        Personal Data that We have collected about You.
      </p>
      Our Service may give You the ability to delete certain information about
      You from within the Service.
      <p className="mb-3 dark:text-gray-300">
        You may update, amend, or delete Your information at any time by signing
        in to Your Account, if you have one, and visiting the account settings
        section that allows you to manage Your personal information. You may
        also contact Us to request access to, correct, or delete any personal
        information that You have provided to Us.
      </p>
      <p className="mb-6 dark:text-gray-300">
        Please note, however, that We may need to retain certain information
        when we have a legal obligation or lawful basis to do so.
      </p>
    </div>
  );
};

export default PrivacyPolicy;
